micronaut:
  application:
    name: buxAssignment
  header:
    enabled: true
  authKey: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyZWZyZXNoYWJsZSI6ZmFsc2UsInN1YiI6ImJiMGNkYTJiLWExMGUtNGVkMy1hZDVhLTBmODJiNGMxNTJjNCIsImF1ZCI6ImJldGEuZ2V0YnV4LmNvbSIsInNjcCI6WyJhcHA6bG9naW4iLCJydGY6bG9naW4iXSwiZXhwIjoxODIwODQ5Mjc5LCJpYXQiOjE1MDU0ODkyNzksImp0aSI6ImI3MzlmYjgwLTM1NzUtNGIwMS04NzUxLTMzZDFhNGRjOGY5MiIsImNpZCI6Ijg0NzM2MjI5MzkifQ.M5oANIi2nBtSfIfhyUMqJnex-JYg6Sm92KPYaUL9GKg
  lang: nl-NL,en;q=0.8

trade:
  server:
    url: ws://localhost:8080/subscriptions/me
    buyUrl: https://api.beta.getbux.com/core/21/users/me/trades
    sellUrl: https://api.beta.getbux.com/core/21/u sers/me/portfolio/positions/